name: Deploy docs
on:
    push:
        branches:
            - main
jobs:
    build-libary:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ./
        steps:
            - uses: actions/checkout@v2
            - uses: bahmutov/npm-install@v1
            - run: yarn build

    build-docs:
        needs: [build-libary]
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: example
        steps:
            - uses: actions/checkout@v2
            - uses: bahmutov/npm-install@v1
            - run: yarn build
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.ACCESS_TOKEN }}
                  publish_dir: ./example/dist
